### ISSUE TITLE
Code Standards & their enforcing for RIR

### ISSUE THREAD

**Issue by petamaj** [reactorlabs/rir#15]
In the past we tried numerous ways to (a) define and (b) enforce coding standards for `rir`. It never really worked perfectly. The issue of this thread should serve as a discussion to this issue with the following goals:

- agree on enforcement policy
- agree on coding standards

**Comment by petamaj** [comment]
*Enforcement Policy*

Ignore (obviously) what is in forks, anything that goes into master, i.e. all pull requests must pass a clang-format (or other format) check to be accepted. 

*Coding Standards*

Instead of devising a complete set of rules that should be applied to the code as most clang-format instances do, let's agree on a smaller set of things that are forbidden and that would be restructured if found. Ideally this would give us the flexibility of formatting the code to be well readable, while maintaining consistency.

**Comment by o-** [comment]
I agree!

Currently our code should mostly adhere to our [.clang-format](https://github.com/reactorlabs/rir/blob/master/.clang-format).

With this one I am mostly happy. @peta you mentioned that you would like to change AllowShortFunctionsOnASingleLine to not allow single line functions. I think I have experimented with that but given up due to incompatibilities between different clang version. But we should try again!

That being said, like you in general I would actually prefer a more liberal approach where only some rules are enforced and not the whole codebase is automatically pretty-printed (because there is a huge space in between we want nice code and there is only one nice code). The problem is so far I did not find any tool which can do this.

Enforcing it in the integration tests is a good idea!

Note: not all versions of clang-format behave the same way! So it could happen that on commit the commit hook formats it with clang-format-3.5 but then a hypothetical travis check will run clang-format-3.8 and will yell. Imho this is another argument to use the more liberal approach!

Some of the hard fought compromises that I think we want to keep is
- some line length limit (currently 80, but we can talk about raising it to 100 or 120)
- four space indentation
- no trailing white space
- { starts not on its own line

One issue I have with the current clang format:
In the compiler we often write instruction streams using the '<<' operator:

```
code << instr
     << instr
```

So far I have not succeeded at teaching this to clang-format.

**Comment by petamaj** [comment]
Yeah, the different versions are super annoying - just having our own definition file should perhaps fix this. Also, maybe not use clang-format if it won't be able to do what we want? There are others that can do the job, like astyle & friends. 

I am ok with line limits and I do not care that much about the actual height since they are all too small anyways, especially if doxygen comments (`/** ... */`) can word wrap - most modern editors I use have abysmal support for non-word wrapped comments and refixing the lines is super annoying. 

I love 4 spaces! Definitely no trailing whitespace. `{` should never start on its own line. (i.e. agree! agree! agree!)

My own pet hates:

- **oneliners** i.e. if, loop, function bodies on the same line if they are one statement. It makes the code really frustrating to me
- inconsistency in `{}`, i.e. if case has them, else case has not
- `{}` for single statements (but the statement should be on its own line and indented)

The next things are impossible to check automatically, but I would think it is good to mention them as well for the general discussion:

- prefix underscores, i.e. `_someName`
- shortening names sacrificing readablity as in *shrtning nms scrifcing rdblty*. 
- using underscores and camel case in different contexts for the same things (as we do currently for instructions), as in `some_instruction_` and `someInstruction`
- trailing underscores to me mean private fields (this might be useless, but it nicely allows public getters of the same name in C++). Using them in different contexts is not something I enjoy

**Comment by aviralg** [comment]
Do we prefer this_name for variables or thisName ?
Do we prefer `_private` for private variables or `private_` ?
It will be helpful to document all the coding standards on the github wiki for this project.

**Comment by petamaj** [comment]
I would prefer camelCase for variables,CamelCase for names (personally). 
Prefix undescores (`_private`) are not compatible with all platforms and are therefore discouraged, which is why the suffix `_` is often used. 

I think is is an effort to discuss the consensus and then distill what we find here into a `md` and into a code formatting tool.
