### ISSUE TITLE
Documentation (general)

### ISSUE THREAD

**Issue by petamaj** [reactorlabs/rir#16]
Look at the code of the stable subsystems (i.e. the compiler, IR instructions, IR representation from C++ and C's point of view, Interpreter, analysis framework, buildsystem, running the tests) and for each of them, create a markdown (`.md`) document in say the `docs` folder that would give an overview of the the given system works. 

These docs should not go into the detail in code comments should go to, but rather provide an introduction to the issues and workflows involved and hints on proper usage. 

In the future these docs are supposed to be kept in sync with code during code reviews. 

> This is for more people, each one can pick different system to document.

**Comment by aviralg** [comment]
Another approach could be to have a README.md for each directory (subsystem) which contains the documentation for that subsystem. This way, the github interface automatically displays it when the directory is opened and it may be easier to remember to update it whenever the subsystem is updated. We can then create soft links to these files in the docs folder for those who want the whole documentation.
We could reflect these files on the github project wiki.

Since I have to work on the analysis framework, I will also document it.

**Comment by petamaj** [comment]
Yeah, having readme's is fine - I am slightly worried that we will not have a unique folder-feature mapping necessary for readme files, but maybe this will force us:)

Thanks!
