### ISSUE TITLE
Performance dashboard links broken

### ISSUE THREAD

**Issue by jimhester** [reactorlabs/rir#961]
The landing page works, but clicking on the compare button gives a `ERR_TOO_MANY_REDIRECTS` error. e.g. https://rir-benchmarks.prl.fit.cvut.cz/diff?kind=diff&warmup=5

**Comment by o-** [comment]
Thanks for the comment, I think it is more of a UX issue, if you select nothing to compare, then apparently it has some bug. It's not polished since so far we just used it internally. I added the following bit of text to the documentation, hope that explains what to do:

`Select two jobs to compare against, to compare against GNU R, or FastR select all first.`

**Comment by jimhester** [comment]
Ah, I misunderstood the UX, got it now, thanks!
